org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# JMC Innovators Release Signing Configuration
JMC_RELEASE_STORE_FILE=../jmc_release.jks
JMC_RELEASE_STORE_PASSWORD=JMCInnovators@2026
JMC_RELEASE_KEY_ALIAS=jmc_release_key
JMC_RELEASE_KEY_PASSWORD=JMCInnovators@2026
