plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jmcinnovators.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.jmcinnovators.app"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.0.2"
    }

    signingConfigs {
        debug {
            storeFile file("${rootDir}/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
